### ISSUE TITLE
Solution Singly_linked_list/RemoveFirst incorrect

### ISSUE THREAD

**Issue by alexanderpeerdeman** [lukasroehr/nabla_codemonkeys_solutions#3]
Die hier angegebene Lösung funktioniert nicht immer. Bei mehrmaligen drücken auf den Absenden-Button werden manchmal Testfälle generiert, die von Nabla nicht akzeptiert werden.

Im Moment habe ich noch keine bessere Lösung, aber melde mich wieder

**Comment by alexanderpeerdeman** [comment]
Es könnte allerdings auch gut sein, dass der Nabla-Administrator zu wenig Zeit für die Ausführung des Algorithmus festgelegt hat (bzw. Serverlast nicht beachtet hat) und deshalb ein Timeout geliefert wird.

**Comment by julienschroeter** [comment]
Scheint an den derzeit stark ausgelasteten Servern zu liegen. Die Lösungen funktionieren im Normalbetrieb korrekt.
